// <auto-generated />
using System;
using Ba_DemoAPI.Confixdb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ba_DemoAPI.Migrations
{
    [DbContext(typeof(DBconnect))]
    [Migration("20210818161720_V1")]
    partial class V1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ba_DemoAPI.EF.Nhanvien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Diachi")
                        .HasColumnType("char(30)");

                    b.Property<string>("Gioitinh")
                        .HasColumnType("char(10)");

                    b.Property<string>("Manv")
                        .HasColumnType("char(8)");

                    b.Property<DateTime>("Ngaysinh")
                        .HasColumnType("Date");

                    b.Property<string>("Phong")
                        .HasColumnType("char(15)");

                    b.Property<string>("Ten")
                        .HasColumnType("char(20)");

                    b.HasKey("ID");

                    b.ToTable("Nhanvien");
                });

            modelBuilder.Entity("Ba_DemoAPI.EF.Password", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Manv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Passwords");
                });
#pragma warning restore 612, 618
        }
    }
}
